### PR TITLE
ILS / LOC Fixes

### LINKED ISSUE #2236: OPFA
# Airport ICAO
OPFA

# Runway(s) with ILS
03
# References (Official sources/charts)
bandicam 2021-04-07 20-38-02-314

# Are you working on this?

Yes

### LINKED ISSUE #2237: OPQT
# Airport ICAO
OPQT

# Runway(s) with ILS
13L
# References (Official sources/charts)
bandicam 2021-04-07 20-43-02-938

# Are you working on this?

Yes

### LINKED ISSUE #2307: OPMT
# Airport ICAO
OPMT
 

# Runway(s) with ILS
36
# References (Official sources/charts)
bandicam 2021-04-13 22-33-48-410

# Are you working on this?

Yes

### LINKED ISSUE #2308: OPPS
# Airport ICAO
OPPS

# Runway(s) with ILS
35
# References (Official sources/charts)
bandicam 2021-04-13 22-36-34-708

# Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by USMN13**
OPFA (Fixes #2236 )
OPQT (Fixes #2237)
OPMT (Fixes #2307)
OPPS (Fixes #2308)

### CODE REVIEW

**Review by velocity23 — APPROVED** [review]

**Review by MajorTomMueller — APPROVED** [review]

**Comment by velocity23** [comment]
Do you want this merged @USMN13?

**Comment by USMN13** [comment]
I think I want to use this pull request for more issues, is that ok?

**Comment by brennanhackard** [comment]
Yes, that's fine. I'll convert it to a draft for you

**Comment by USMN13** [comment]
I want it merged now Thanks

**Review by velocity23 — APPROVED** [review]

**Pull request merged**
