### PR TITLE
LIPO ILS

### PR DESCRIPTION
**Pull request by Spinxzl**
Edited. 1st ILS

### CODE REVIEW

**Comment by Spinxzl** [comment]
Have fixed and recommited

**Comment by Adrien-Z** [comment]
I don't see your changes, are you sure you pushed the commit to this pull request?

**Comment by Spinxzl** [comment]
@Adrien-Z Should i close this and make a new PR? I can't seem to get this one to work

**Comment by dushyants19** [comment]
Wait a sec, travis is doing something

**Comment by Spinxzl** [comment]
It worked! I think

**Comment by dushyants19** [comment]
Yes it did.

**Comment by Adrien-Z** [comment]
I'll quickly review it and merge it if everything's okay. :)

**Pull request merged**
