### PR TITLE
MMLP - ILS

### PR DESCRIPTION
**Pull request by lalomarlin**
Changed ILS RW 18

### CODE REVIEW

**Comment by lalomarlin** [comment]
That wasn't suposed to be done

**Comment by dushyants19** [comment]
Want me to merge or not?

**Comment by lalomarlin** [comment]
Is it possible to merge both files and close MMTO too?

**Comment by dushyants19** [comment]
Yes it is possible to make changes for multiple airports in one pull request

**Comment by lalomarlin** [comment]
Please merge it 😉

**Pull request merged**
