### PR TITLE
GOBD - ILS added

### PR DESCRIPTION
**Pull request by ewanfleming**
Added the ILS at GOBD.

### CODE REVIEW

**Comment by dushyants19** [comment]
Glideslope is incorrect.

**Comment by ewanfleming** [comment]
Details? Cmon, how am I meant to fix it with that info? 🙄

**Comment by dushyants19** [comment]
Read the guide?

**Comment by dushyants19** [comment]
https://github.com/InfiniteFlightAirportEditing/Navigation/wiki/Editing-ILS-approaches

**Comment by ewanfleming** [comment]
Got it, I thought you meant the glide scope file in general

**Comment by ewanfleming** [comment]
^ fixed

**Pull request merged**
