### PR TITLE
Various Fixes 2020-09-30

### LINKED ISSUE #66: KJFK

### LINKED ISSUE #130: UUEE
Need to adjust ILS for runways, once airport is in the repository

### LINKED ISSUE #193: EDDM
Both runways equipped with ILS were moved a bit in the editing process

### LINKED ISSUE #734: OMAA
Just flew into Abu Dhabi, and all the approaches are GPS. This isn't realistic. Needs some ILS.

### LINKED ISSUE #834: SKBG
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway Moved

# Runway(s) with ILS: (If any)

35

# References: (Official sources/charts)

http://www.aerocivil.gov.co/servicios-a-la-navegacion/servicio-de-informacion-aeronautica-ais/Documents/13%20SKBG.pdf

### LINKED ISSUE #1662: VOBL
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

All Runways

# References: (Official sources/charts)

https://aim-india.aai.aero/sites/default/files/aip_supplements/AIPS_2019_145.pdf

Page 16-17

### LINKED ISSUE #1665: HAAB
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

Rwy 25R / 25L

# References: (Official sources/charts)

ILS Rwy 25L

ILS Rwy 25R

### LINKED ISSUE #1672: RJAA
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 16/R 34L/R >

# References: (Official sources/charts)

< 
16LILS
16RILS
34LILS
34RILS

 >

### LINKED ISSUE #1677: EGNX
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

09/27

# References: (Official sources/charts)

https://www.aurora.nats.co.uk/htmlAIP/Publications/2020-08-13-AIRAC/html/index-en-GB.html
https://www.aurora.nats.co.uk/htmlAIP/Publications/2020-08-13-AIRAC/html/index-en-GB.html

Check new commit of airport :)

### PR DESCRIPTION
**Pull request by Velocity23**
Fixes #834, Fixes #1665, Fixes #193, Fixes #1662, Fixes #1672, Fixes #734, Fixes #1677, Fixes #66, Fixes #130.

Please scrutinize this one, testing out my new semi-automated Nav Editing UI.

### CODE REVIEW

**Comment by AleksanderIF** [comment]
Any reasons why it was fixed?

**Comment by Czechoslovaki** [comment]
Why are some edited again?

**Comment by MajorTomMueller** [comment]
May be someone missed that we aren't have authority over them.

**Comment by Velocity23** [comment]
@AleksanderIF Sorry, UUEE was on a list I had but I didn't see your PR. I'll revert that one to avoid conflicts. 

@Czechoslovaki I went through the recently edited airports (last nav push and recent commits to Airports) and wrote down ICAOs, then edited those. I just referenced the issues so it's on record there that I've done them recently.

**Review by RyanEpps — APPROVED** [review]

**Pull request merged**
