### PR TITLE
ILS Fixes

### PR DESCRIPTION
**Pull request by 2000rpm**
RKSM
RWY20 revised

ILS 20

### CODE REVIEW

**Comment by MajorTomMueller** [comment]
Could you elaborate about the fix you made for RKSO @2000rpm

**Comment by 2000rpm** [comment]
I found some old ILS chart for RKSO.
[RKSO.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4671552/RKSO.pdf)

**Comment by 2000rpm** [comment]
I use apt.dat for reference.

**Comment by MajorTomMueller** [comment]
You are aware that the chart you refer to is completely outdated cause it was from a period of heavy construction work at Osan?
3B313112-3D0D-47AD-8CA0-D8DCF1AE6B02
Don’t mess it up.

**Comment by 2000rpm** [comment]
I didn't use it for any change for current data of RKSO.
I thought I need to submit some file like it, so I surfed for some info.
I knew now those are for new ILS, not already exist.

Those data that I changed was referred by airport data.

**Pull request merged**
