### PR TITLE
ADPOP added

### PR DESCRIPTION
**Pull request by dushyants19**
http://opennav.com/waypoint/IN/ADPOP

### CODE REVIEW

**Comment by ItsW1ll** [comment]
i have the latitude as being 19.0508333?

**Comment by dushyants19** [comment]
I used 3.20 seconds

**Comment by Adrien-Z** [comment]
I believe the latitude should be `19.050889` and the longitude `68.000028`.

**Comment by dushyants19** [comment]
I just did it for amazing tutorial but ok

**Pull request merged**
