### PR TITLE
ILS / LOC Fixes

### LINKED ISSUE #2213: KFLG
# Airport ICAO
KFLG

# Runway(s) with ILS
21
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/05034IL21.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2215: KFNL
# Airport ICAO
KFNL

# Runway(s) with ILS
33
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/05677IL33.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2216: KFNT
# Airport ICAO
KFNT

# Runway(s) with ILS
09, 27
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/00618IL9.PDF
https://aeronav.faa.gov/d-tpp/2103/00618IL27.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2217: KFOK
# Airport ICAO
KFOK

# Runway(s) with ILS
24
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/00996IL24.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2218: KFRM
# Airport ICAO
KFRM

# Runway(s) with ILS
31
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/05353IL31.PDF

# Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by zhf21**
KFLG (Fixes #2213)
KFNL (Fixes #2215)
KFNT (Fixes #2216)
KFOK (Fixes #2217)
KFRM (Fixes #2218)

### CODE REVIEW

**Comment by zhf21** [comment]
All done. Will resume when this issue is merged to obey by the five commit rule.

**Review by MajorTomMueller — CHANGES_REQUESTED** [review]
You have used different elevations for LOC and GS, while this can be the case in real world it is not the case in Infinite flight. Use the airfield elevation from the apt.dat file of the airport.

**Comment by zhf21** [comment]
For which airport, @MajorTomMueller?

**Comment by MajorTomMueller** [comment]
More then one, just check through all elevations

**Comment by zhf21** [comment]
@MajorTomMueller - everything is correct in terms of elevation. I cross-checked the GS and LOC files and the commits, and the elevations match for each respective airport. I think you were looking at the deleted files and comparing those.

**Review by velocity23 — APPROVED** [review]

**Pull request merged**
