### PR TITLE
EGKB ILS

### PR DESCRIPTION
**Pull request by ewanfleming**
Fixed the ILS for EGKB. First ILS edit ever so will probably get rejected but whatever

### CODE REVIEW

**Comment by dushyants19** [comment]
yes

**Comment by ItsW1ll** [comment]
Ewan with this PR you will need to create another pull request as this one is merging with master instead of the development branch

**Comment by ewanfleming** [comment]
Ok, will do that. The dev branch wasn’t created when I committed that so I’ll make another one

**Comment by ItsW1ll** [comment]
yeah, i had to create another one for EGBB

**Pull request closed without merging**
