### PR TITLE
ILS / LOC Fixes

### LINKED ISSUE #2292: DAUB
# Airport ICAO
DAUB

# Runway(s) with ILS
31
# References (Official sources/charts)
image0

# Are you working on this?

Yes

### LINKED ISSUE #2294: KDMA
# Airport ICAO
KDMA

# Runway(s) with ILS
12, 30
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/00429ILY12.PDF
https://aeronav.faa.gov/d-tpp/2103/00429ILY30.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2296: KDOV
# Airport ICAO
KDOV

# Runway(s) with ILS
01, 19
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/00562I1C2.PDF
https://aeronav.faa.gov/d-tpp/2103/00562IL19.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2297: KECP
# Airport ICAO
KECP

# Runway(s) with ILS
16
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/10416I16SAC1_2.PDF

# Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by zhf21**
DAUB (Fixes #2292)
KDMA (Fixes #2294)
KDOV (Fixes #2296)
KECP (Fixes #2297)

### CODE REVIEW

**Comment by zhf21** [comment]
Good to go!

**Comment by MajorTomMueller** [comment]
There is no need to edit the ILS of DAUB.

**Comment by MajorTomMueller** [comment]
The whole pull request is crap, you just edited random airports that where long in the repository.

**Comment by zhf21** [comment]
Don't you ever call my work crap. None of these airports were "random." All had fixes to be made, most prominently elevation changes, ILS additions, etc. I'm offended by your lack of care for those who try to better Infinite Flight. Upper management will be made aware of this.

**Comment by MajorTomMueller** [comment]
Why don’t you note down in the issue what changes you are going to do? That’s what the issue tracker is for.
It is not specifically asked for, but it is extremely helpful.
The glideslope frequency was correct at DAUB, I have checked that, and I have linked you the source.
Have you checked that the elevation you are referring to is correct?
Have you checked that the bearing of the runway in the apt.dat file is corresponding with the published bearing for the ILS? They are not always the same!
From all the changes you proposed is only one valid in my eyes, that is the adding of the "new" KDMA ILS.
IF-LLC ignore either the bearing as well as the elevation fand the GS frequency from this file anyway. There is no need to adjust minor discrepancies, especially when they are oriented on the apt.dat file values different from real world data.
What we need to fit to apt.dat is
- ICAO
- Rwy number
- Identifier of LOC/ILS
The rest has no effect in IF at this time, and for further use in future it is most likely that the real world data are needed.
Keep KDMA Rwy 12, the rest is unnecessary worsening.

**Comment by zhf21** [comment]
When I learned nav editing from a former supervisor (r.i.p. Claudio), he told me that certain information in the apt.dat gets used despite what the charts say (i.e., bearing, altitude, etc.). In theory, yes, what is in the apt.dat should be the same as charts, but not all are. Furthermore, I've never had an issue with these "small" adjustments until now. 

Even if Infinite Flight does not use the Glideslope.json file, or prioritizes the LOC.json file, I see no reason as to why there should be a discrepancy between information of the same airport. 

If you want me to revert the DAUB commit, fine. I see no reason to revert my other edits as they are fit.

**Comment by MajorTomMueller** [comment]
To make a point clear that was misleading: 
I do see you are a Good Airporteditor @zhf21 , and. Along something in here "crap" would be to harsh.
My wording was inappropriate, I do apologise for that, I am not a Native English speaker.
Hist. Keep your pull request to the necessary addition of Rwy 12 at KDMA and ever is fine.

**Comment by zhf21** [comment]
DAUB reverted. Ready for review.

**Review by velocity23 — APPROVED** [review]

**Comment by zhf21** [comment]
Can this be merged? I would like these changes to be reflected in the upcoming update. Thanks.

**Pull request merged**
