### PR TITLE
ILS / LOC Fixes

### LINKED ISSUE #2230: KTVF
# Airport ICAO
KTVF

# Runway(s) with ILS
31
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/05201IL31.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2231: KTYQ
# Airport ICAO
KTYQ

# Runway(s) with ILS
36
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/05438IL36.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2232: KUES
# Airport ICAO
KUES

# Runway(s) with ILS
10
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/05078IL10.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2233: KVAD
# Airport ICAO
KVAD

# Runway(s) with ILS
18L, 36R
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/00435ILY18L.PDF
https://aeronav.faa.gov/d-tpp/2103/00435ILY36R.PDF

# Are you working on this?

Yes

### LINKED ISSUE #2235: KTNT
# Airport ICAO
KTNT

# Runway(s) with ILS
N/A - Removal of RWY 09 ILS
# References (Official sources/charts)
35BB8288-42CF-434D-8662-7B296368BF56

# Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by zhf21**
KTNT (Fixes #2235)
KTVF (Fixes #2230)
KTYQ (Fixes #2231)
KUES (Fixes #2232)
KVAD (Fixes #2233)

### CODE REVIEW

**Comment by zhf21** [comment]
Forgot a comma. 😐

**Comment by zhf21** [comment]
Completed. Sorry for multiple commits with KVAD. I placed a comma in two places instead of one.

**Comment by MajorTomMueller** [comment]
Please make a issue for KTNT with a reference.

**Review by MajorTomMueller — APPROVED** [review]

**Comment by zhf21** [comment]
> Please make a issue for KTNT with a reference.

How do I reference an airport with no ILS?

**Comment by zhf21** [comment]
Requesting a merge (@velocity23).

**Pull request merged**
